### PR TITLE
feat: add url filter and localize method for docs

### PR DESCRIPTION
**Pull request by jeremydw**
- This adds a `localize` method to documents which fixes a bug where `!pod.doc` yaml type was used, a document in the pod's default locale would be returned rather than a (better default) where the current document's locale is returned.
- Adds an extremely useful `url` nunjucks filter which adds the [functionality from here](https://github.com/blinkk/amagaki-starter/blob/main/amagaki.ts#L32) to core

### CODE REVIEW

**Comment by Zoramite** [comment]
Why do you use the relative url for the `|url`?

**Comment by jeremydw** [comment]
> Why do you use the relative url for the `|url`?

It's mainly there as a "sane default". Since sometimes staging or testing environments mount the site with a path other than the root, using relative URLs allows the staging/testing/dev sites to work without modifying all other URLs.

I think we should make the usage of relative (and localize) optional, so I'll add options to the URL filter to enable or disable those features, but using a default of relative (and localized, and fingerprinted) is a good choice for the majority of URLs.

**Comment by jeremydw** [comment]
OK, this is updated and a bit better now.

- Broke the logic out from Nunjucks and moved it to a static method on the `Url` object
- Naming it a "common" URL, aka the URL you'd most commonly use
- Added a bunch of tests

**Comment by jeremydw** [comment]
Abandoning this as we are shifting focus to React, no longer needing Nunjucks filters as part of the tooling

**Pull request closed without merging**
